### ISSUE TITLE
Development style

### ISSUE THREAD

**Issue by 64kramsystem** [ticketsolve/activetrigger#8]
There are two approaches to developing this project:

1. directly on the (central) repository (ticktesolve-style)
2. on forks

I think we should work using forks; this is the typical structure for open source projects, and in particular, if in theory we'll have contributors, it'll be odd to have a mixed style.

Input welcome!

**Comment by guilhermecortes** [comment]
Makes sense to me! It will be interesting for me because I haven't worked with this way before :)

**Comment by shanly** [comment]
good with me as well

**Comment by shivabhusal** [comment]
sounds good!

**Comment by 64kramsystem** [comment]
Ok, settling for fork-based workflow.
